behaviors:
  My Behavior:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      buffer_init_steps: 1000
      learning_rate: 0.0003
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: resnet
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    checkpoint_interval: 40000
    keep_checkpoints: 30
    max_steps: 400000
    summary_freq: 2000
    threaded: true